---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop athelcall-cnt
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm athelcall-cnt
      ignore_errors: yes

    - name: remove athelcall-image
      command: docker rmi athelcall-img
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t athelcall-img .

    - name: run container
      command: docker run -d --name athelcall-cnt -p 5000:80 athelcall-img